##
## Perfil de desarrollo
spring.profiles.active=local

##
## Configuración del aplicativo
spring.application.name=gestor_ws
server.servlet.context-path=/gestor-ws
server.port=8090

##
## Configuración de swagger
## http://localhost:8090/gestor-ws/swagger-ui/index.html
## /gestor-ws/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true
## Configuración de la documentación
openapi.info.title=GestorWS
openapi.info.version=1.0.0
openapi.info.description=API de gestion de aplicaciones, usuarios y parametrizacion
openapi.info.contact.name=13Aplicaciones
openapi.info.contact.url=http://localhost:8090/gestor-ws/swagger-ui/index.html
openapi.info.contact.email=omargo33@gmail.com

##
## Seguridades
contexts.excluded-security=/login,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/actuator/**
## Agregar a las variables de entorno COOFING_CLIENT_SECRET y COOFING_URL_KEYCLOAK
spring.security.oauth2.client.registration.keycloak.client-id=gestor002-client
## spring.security.oauth2.client.registration.keycloak.client-secret=${COOFING_CLIENT_SECRET:NGrjAmonCxkiOlUJ1Wj1KgeS5mKRZfmG}
spring.security.oauth2.client.registration.keycloak.client-name=Keycloak
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak
spring.security.oauth2.client.provider.keycloak.issuer-uri=${COOFING_URL_KEYCLOAK:http://localhost:8080}/realms/portal-realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COOFING_URL_KEYCLOAK:http://localhost:8080}/realms/portal-realm

##
## Configuración de CORS (separados por comas y sin espacios)
cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://example.com,http://localhost:5002
cors.allowed-methods=GET,POST,PUT,DELETE,PATCH

##
## Configuracion de cliente de adminitración
## https://www.baeldung.com/spring-boot-admin
spring.boot.admin.client.url=http://localhost:8100
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

##
## Configuración de log: NONE, TRACE, DEBUG, INFO, WARN, ERROR
logging.level.root=WARN
## logging.level.org.springframework=INFO
## logging.level.org.hibernate=INFO
## logging.level.org.springframework.orm.jpa=DEBUG
logging.level.com.aplicaciones13=INFO
