spring.application.name=keycloak

# Configuración de Keycloak
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=portal-realm
keycloak.resource=portal-client
keycloak.credentials.secret=tu-secreto
keycloak.admin.username=root
keycloak.admin.password=12341234s

# Configuración del servidor
server.port=8070