##
## Configuración del servidor
server.port=8070
server.servlet.context-path=/keycloak-ws
spring.application.name=keycloak

##
## Configuración de swagger
## http://localhost:8092/keycloak-ws/swagger-ui/index.html
## /gestor-ws/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.filter=true
## Configuración de la documentación
openapi.info.title=GestorWS
openapi.info.version=1.0.0
openapi.info.description=API de gestion de keyCloak
openapi.info.contact.name=13Aplicaciones
openapi.info.contact.url=http://localhost:8070/keycloak-ws/swagger-ui/index.html
openapi.info.contact.email=omargo33@gmail.com

##
## Configuración de Keycloak
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=portal-realm
keycloak.resource=portal-client
keycloak.credentials.secret=tu-secreto

##
## Configuración credenciales de Keycloak para master admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin123

##
## Configuracion de cliente de adminitración
## https://www.baeldung.com/spring-boot-admin
spring.boot.admin.client.url=http://localhost:8100
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Propiedades de Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=passport-group
kafka.topic.passport=keyCloak-Topic

