##
## Configuración del servidor
server.port=8070
spring.application.name=keycloak

##
## Configuración de Keycloak
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=portal-realm
keycloak.resource=portal-client
keycloak.credentials.secret=tu-secreto

##
## Configuración credenciales de Keycloak para master admin-cli
keycloak.admin.username=admin
keycloak.admin.password=admin123

# Propiedades de Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=passport-group
kafka.topic.passport=keyCloak-Topic

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.aplicaciones13.orquestador.model
spring.kafka.consumer.properties.spring.json.value.default.type=com.aplicaciones13.orquestador.model.Passport