
##
## Configuracion de la base de datos postgresql
spring.datasource.url=jdbc:mysql://localhost:3306/GS_002_01?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=user_gs
spring.datasource.password=12341234s

## spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456s}
## spring.jpa.properties.hibernate.default_schema=GS_002_01

##
## Configuracion de JPA
spring.jpa.open-in-view=false
## spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

##
## Configuracion de redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=123456s
spring.cache.type=redis
spring.cache.redis.time-to-live=60000
## spring.cache.redis.cache-null-values=false