##
##
## Docker para administrar contenedores del desarrollo del proyecto gestor002
## 
## Servidor de base de datos msyql latest
## Servidor de nxinx latest
## Servidor de Spring Boot Admin java 

version: '3.7'

services:
  
  mysql:
    image: mysql:8.0
    container_name: mysql_portal
    ## restart: always
    ##
    ## configuracion de recursos
    mem_limit: 512m
    mem_reservation: 256M
    cpus: 1
    ports:
      - "3306:3306"
    command: 
      --bind-address=0.0.0.0
    environment:
      TZ: America/Bogota
      MYSQL_DATABASE: GS_002_01
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: user
    volumes:
      - ./baseDatos/mysql-files:/var/lib/mysql-files
      - ./baseDatos/mysql-data:/var/lib/mysql
      - ./baseDatos/init.d:/docker-entrypoint-initdb.d
    networks:
      - gestor-network

  nginx:
    image: nginx:latest
    container_name: nginx_portal
    ## restart: always
    ##
    ## configuracion de recursos
    mem_limit: 384m
    mem_reservation: 128M
    cpus: 0.5
    ports:
      - "80:80"
    environment:
      TZ: America/Bogota
    volumes:
      - ./html:/var/www/html
      - ./cert:/etc/nginx/cert
      - ./config:/etc/nginx
    ##network_mode: 
      ##host 
    depends_on:
      - mysql
    networks:
      - gestor-network

  ##
  ## Servidor de keycloak
  keycloak:
    build: keycloak_build
    image: keycloak:26.0
    container_name: keycloak_portal
    ## restart: always
    ##
    ## configuration recursos
    mem_limit: 1024m
    mem_reservation: 512M
    cpus: 1
    environment:
      - TZ=America/Bogota
      - KC_DB_PASSWORD=${KC_DB_PASSWORD} ## clave de base de datos      
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak?allowPublicKeyRetrieval=true&useSSL=false
      - KC_DB_USERNAME=user_keycloak ## usuario de base de datos
      - KC_DB=mysql ## tipo de base de datos
      - KC_HOSTNAME_STRICT_HTTPS=false ## configuracion de host
      - KC_HOSTNAME_STRICT=false ## configuracion de host
      - KC_HTTP_ENABLED=true ## configuracion de host
      - KC_PROXY=edge ## configuracion de proxy
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD} ## clave de keycloak
      - KEYCLOAK_ADMIN=admin ## usuario de keycloak
      - DB_VENDOR=mysql
      - JTA=false
    ports:
      - 8080:8080
    ##network_mode: 
      ##host
    depends_on:
      - mysql
    command:
      - start    
    networks:
      - gestor-network

  ##
  ## Servidor de cache Redis
  redis:
    image: redis:latest
    container_name: redis_portal
    ## restart: always
    ##
    ## configuracion de recursos
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.5
    ports:
      - "6379:6379"
    environment:
      TZ: America/Bogota
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ##network_mode: 
      ## host
    depends_on:
      - mysql
    networks:
      - gestor-network
    
  ## Servicio de mensajeria local para pruebas.
  manager:
    image: manager:0.0.1
    container_name: manager_portal
    ## configuration recursos
    mem_limit: 256m
    mem_reservation: 64M
    cpus: 0.5    
    ## restart: always
    build: manager_build
    ports:
      - 8100:8100    
    network_mode: host
    
networks:
  gestor-network:
    driver: bridge

